.github/workflows/ci.yaml
.github/workflows/formatting.yaml
.github/workflows/license-check.yaml

No tests here yet but run them if as if we did.

Add CI stuff.

---

src/hsm.rs

key share prompt and debug output

---

src/hsm.rs

This allows us to fail earlier in the process minimizing the potential for us to have to reset the HSM.

Persist wrap key to HSM at end of personalization.

---

Cargo.lock
Cargo.toml
src/hsm.rs
src/main.rs

Replace `rusty_secrets` with `vsss_rs`.

---

.github/workflows/ci.yaml
.github/workflows/formatting.yaml
.github/workflows/license-check.yaml
rust-toolchain.toml
src/config.rs

v1.64 only

---

src/hsm.rs

Format key share prints for Epson LX-350

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml
script/burn-cd
script/mount-input
script/oks-lib.sh

Script cleanup

---

Cargo.lock
Cargo.toml
src/hsm.rs

PEM encode addestation certs.

---

src/ca.rs

produce only PEM certs, no text

---

src/hsm.rs
src/main.rs

Verifier to output

---

src/ca.rs

oks: Stop distributing the CSR generated for root keys in output dir.

---

src/ca.rs

Non critical extensions

---

script/burn-cd
script/hash-cd
script/mount-input
script/oks-lib.sh
script/start-session

This commit also adds a few new 'info' log statements to better narrate the process.
this resolves #108

script: Add UTC / Zulu time stamp to log messages.

---

src/hsm.rs
src/main.rs

Move HSM stuff into a struct.

---

script/ceremony

PRINT_DEV, KEY_SPEC and CSR_SPEC env vars should not have been committed

---

src/hsm.rs

Don't print a blank page after the HSM password.

---

specs/production/platform-identity-root-a.keyspec.json
specs/staging/platform-identity-root-a.keyspec.json

Add specs for staging and production platform identity PKI.

---

script/write-output

write-output: add info message about copying ca-state

---

script/import-input

Fix typo in `import-input` script.

---

.github/workflows/formatting.yaml
.github/workflows/license-check.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml
rust-toolchain.toml
src/ca.rs
src/config.rs

an attempt to maintain compatibility w/ next OKOS release

Toolchain upgrade

---

Cargo.lock

... the world keeps turning ...

Update all dependencies.

---

src/hsm.rs

These functions cover the operation to split a secret, deserialize the verifier, verify shares and reconstruct the secret.

Add tests to ensure the feldman stuff works the way we think it does.

---

src/hsm.rs

Add a few test cases (positive) for feldman verifier usage & clean up the process used to reconstitute the backup key.

Hsm restore revive

---

src/hsm.rs

hsm: Define a type for key shares.

---

src/alphabet.rs
src/bin/printer-test.rs
src/hsm.rs
src/lib.rs
src/main.rs

This is easy / possible now that the Hsm type implements RngCore.

Refactor the Alphabet & Hsm types into separate modules.

---

src/cdrw.rs
src/secret_reader.rs

CD devices can have many names.

Search through a list of possible cd device paths.

---

script/write-output
src/cdrw.rs
src/main.rs
src/secret_reader.rs

Increasing sleep time on each retry may be necessary.

CdReader: Retry mount command w/ fixed retry and sleep count.

---

src/cdrw.rs
src/secret_writer.rs

use `blockdev` to detect availability of media in CD drive

---

rust-toolchain.toml
src/secret_writer.rs

This matches the version shipped w/ NixOS 24.11.

Upgrade pinned rust version from 1.79 to 1.81

---

src/main.rs

We've been developing ceremonies as scripts that execute a series of `oks` commands. The `oks ceremony` command hasn't been updated since the provisioning ceremony and keeping it up to date has exceeded the point of deminishing returns.

delete `oks ceremony` command

---

script/handoff

This isn't used in the next ceremony but it will be used in the one after.

handoff: Add printer setup
