src/ca.rs, src/config.rs, src/hsm.rs
This commit also fixes a bug in how we were formatting key ids in various contexts (must be hex, no '0x' prefix).
=> Implement batch processing of CA initialization.

src/config.rs
This will be useful for creating inputs into offline keystore ceremonies.
It's not directly uses here, but I intend to use it in a different project.
=> Add a method to print the JSON representation of a CsrSpec.

Cargo.toml, util/format_csr.rs
This is basically a remake of https://github.com/oxidecomputer/offline-keystore/pull/38, which never made it to the `main` branch.
=> Add the cmdline util for formatting CSRs

util/format_csr.rs
NixOS packages rustc 1.64.0 but `std::io::read_to_string` was added in 1.65. Working around this was less work / risk than updating the OS.
=> Update format_csr to use rustc from NixOS 22.11.

src/hsm.rs, src/main.rs
We use the default auth because this is the first command executed in the upcoming ceremony and so the defaults are all that's available.
=> Add command to dump YubiHSM serial-number using default credential.

src/main.rs
I just had the HSM timeout while generating an RSA4k key even with a 4 minute timeout. I'm tempted to make this timeout infinite but we need some way to know when we need intervention in order for the ceremony to proceed. 5 minutes seems conservative enough while still allowing for a meaningful timeout.
This resolves #85
=> Increase timeout from 2 minutes to 5.

script/start-session
The `mkdir` should have been passed `-p` to begin with. Seting `eou pipefail` isn't explicitly necessary for such a simple script but since our intent is to do this for all scripts we do so here as well.
this resolves #78
=> Make `start-session` script more robust.

src/bin/printer-test.rs, src/hsm.rs
Built offline-keystore-os w/ this branch.  Verified key shares are printed legibly and `oks hsm restore-all` accepted the key shares and restored the backups.
Fixes #77
=> Fix key share printing

Cargo.lock, Cargo.toml, data/gimlet-rot-code-signing-dev-a.keyspec.json, data/gimlet-rot-code-signing-dev-b.keyspec.json, data/gimlet-rot-code-signing-rel-a.keyspec.json, data/gimlet-rot-code-signing-rel-b.keyspec.json, data/psc-rot-code-signing-dev-a.keyspec.json, data/psc-rot-code-signing-dev-b.keyspec.json, data/psc-rot-code-signing-rel-a.keyspec.json, data/psc-rot-code-signing-rel-b.keyspec.json, data/sidecar-rot-code-signing-dev-a.keyspec.json, data/sidecar-rot-code-signing-dev-b.keyspec.json, data/sidecar-rot-code-signing-rel-a.keyspec.json, data/sidecar-rot-code-signing-rel-b.keyspec.json, src/ca.rs, src/config.rs
NXP LP55S69 secure boot requires the last certificate in the chain to have a certificate serial number with the first 4 bytes encoding a magic number and a 16-bit revocation ID.  Extend KeySpecs to allow setting an initial serial number and then use that to cause the RoT certificates to fit the necessary encoding.
Tested by going through a commissioning of a Testing OKS and verifying the resulting certificates have serial numbers conforming to NXP's encoding.
=> Configure certificate serial numbers to conform to LPC55 requirements

src/ca.rs
=> oks: Do not require each cert issued to have a unique `subject`.

src/bin/yhsm.rs, src/main.rs
The `oks` tool has out grown its current form. It's performing two distinct tasks now: automating aspects of our key ceremonies as it was initially intended, and executing individual YubiHSM commands used during development and debugging. The later belongs in a separate tool.
This resolved #46
=> yhsm: Add new command to execute individual yubihsm commands.

script/ceremony, src/ca.rs, src/config.rs, src/hsm.rs, src/main.rs
This includes an exmaple script that automates the whole ceremony while challenging the user for the password just once. This script will likely become another rust command line tool that does effectively the same thing.
this resolves #83 and #112
=> Accept password for auth & creation of the auth credential through env.

src/ca.rs, src/hsm.rs, src/main.rs
Using the wrapper makes things more clear / obvious. Having to call `zeroize()` manually is error prone.
resolves #127
=> Zeroize secrets with the Zeroizing wrapper.

src/ca.rs
the `deviceIdentityPolicy` oid is defined by us: https://github.com/oxidecomputer/oana/pull/18, the rest come from the DICE certificate spec.
=> Add policy OIDs for device identity & it's dice descendants.

Cargo.lock, Cargo.toml, src/bin/printer-test.rs, src/hsm.rs
- Avoid visually simlar characters when generating HSM passwords
- Eject paper after printing HSM password
- Use byte and byte string literals instead of converting from unicode
- printer-test for hsm password printouts
- include notice about whitespace in printouts
=> Batch of printer formatting fixes

src/bin/yhsm.rs, src/hsm.rs, src/main.rs
The `ceremony` command remains unchanged but individual `hsm` commands now allow the caller to disable the creation of backup /wrap keys when executing `hsm initialize` and the backing up of keys created by the `hsm generate` command.
=> Allow caller to make HSM object backups optional w/ `--no-backup`.

src/ca.rs
This gives us a place to save CSRs if we choose to.
=> Add 'csr' to dirs created in ca-state.

Cargo.lock
0.37.27 is the latest from the 0.37 series. Moving to the 0.38 release of rustix requires upgrading env_logger from 0.10 to 0.11 and that starts a cascade of incompatibility that ends at a required upgrade to clap that requires a version of rustc >= 1.70 and we're currently pinned to 1.69 till we upgrade nixos past 23.05.
=> Cargo.lock: upgrade rustix 0.37.11 -> 0.37.27

.github/workflows/formatting.yaml, .github/workflows/license-check.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, Cargo.lock, Cargo.toml, rust-toolchain.toml, src/ca.rs
First step toward 0.2.0 release. This gets us (I think) the latest deps compatible w/ the rustc (v1.69) shipped w/ NixOS 23.05.
=> Oks 0.2.0 pre

Cargo.lock
Both versions in use were yanked.
=> Upgrade ahash and hermit-abi

Cargo.lock, Cargo.toml, src/ca.rs
The `Client` type previously had a `Drop` implementation that closed the session if the Client had an open one. This seems to have caused problems in other downstream projects and was subsequently removed: https://github.com/iqlusioninc/tmkms/issues/37
https://github.com/iqlusioninc/yubihsm.rs/pull/265
The replacement was to provide a `session()` function that returns an Arc / MutexGuard wrapped reference to the optional session. This isn't useful for us here because we don't and AFAIK can't take ownership of the session which we need because the Sesison::close function consumes the session (it can't be reopened). Our solution requires an upstream change to the `Client` type adding a `close_session` function that just closes the session if one is open.
This resolves #190
=> Use session close function from oxide fork of yubihsm.rs.

Cargo.lock, Cargo.toml
The fix to the session exhaustion issue warrants a bump from `pre0` to `pre1`.
=> Cargo.toml: Update version to 0.1.0-pre1

script/hash-cd, script/oks-lib.sh
Reading the digest as a single line of hex characters off of the laptop screen is difficult. Breaking the digest up into multiple lines w/ spaces between each byte makes it much easier.
=> pretty print the sha256 hash generated by `hash-cd`

script/mount-input
This is required for all ceremonies that require the use of the CAs and are carried out after the initial provisioning. This state must be restored *and* writen as output for use in ceremony n+1
=> Restore `ca-state` to writable part of the disk.

script/signing-ceremony
This script takes a password from the caller and uses the `oks hsm serial-number` command to determine whether or not the password is correct. It relies on the OKS_PASSWORD environment variable accepted by `oks`. It also implements the retry logic required by the ceremony script.
=> Add script for signing ceremony

src/hsm.rs
Speculating about the origin of this behavior wasn't smart. It's also probably wrong: RNGs are usually pretty quick, the primality test is probably a better candidate for blame. Better to stick to the facts.
=> Fixup bad comment.

src/bin/yhsm.rs, src/hsm.rs
YubiCo docs state that only 1-60 are valid index values. I've set this value to well beyond 60 in testing. These docs don't say what happens when the index (u16) rolls over.
https://docs.yubico.com/hardware/yubihsm-2/hsm-2-user-guide/hsm2-cmd-reference.html#set-log-index-command
=> yhsm: Add command for dealing with the audit log.

Cargo.lock, Cargo.toml, src/ca.rs, src/config.rs, src/main.rs
This commit refactors the functions that previously made up the `ca` module into a type. This is intended to make the code more legible and hopefully more maintainable as well. A significant part of this work was moving the output handling out of the `ca` module and up into `main`. The `ca` module is now limited to processing inputs (key / csr / dscr specs) and generating outputs. This simplifies the `ca` module significantly and moves policy decisions like where to write output files further up the call stack.
The config module was updated to allow serialization of the KeySpec type back to json. We do this so that we can use the type system to ensure that the `Ca` type is only passed valid KeySpecs. Internally this type persists the KeySpec alongside other CA state info which requires …
=> Refactor `ca` module into a type.

src/bin/printer-test.rs, src/hsm.rs, src/lib.rs, src/main.rs, src/secret_reader.rs, src/secret_writer.rs, src/util.rs
More cleanup work, this time moving the code that exports / imports secrets like passwords & key shares into its own module. This is in anticipation of future work to support new I/O methods not the printer.
=> Share read write

Cargo.lock, Cargo.toml, src/hsm.rs, src/main.rs
This allows us to replace use of the ChaCha20 Rng w/ the YubiHSM RNG / Hsm type. The RngCore API fills in a buffer provided by the caller while the YubiHSM `get_pseudo_random` allocates & returns a Vec<u8>. This impedance mismatch between the two APIs makes for unnecessary allocation but saves us some code.
=> Implement RngCore and CryptoRng for Hsm.

Cargo.lock, Cargo.toml, src/backup.rs, src/bin/printer-test.rs, src/hsm.rs, src/lib.rs, src/main.rs, src/secret_reader.rs, src/secret_writer.rs
This is an intermediate state. Eventually the Hsm type won't touch any of they backup key creation and splitting. The main module will take over that part and the Hsm module will continue to deminish.
=> Move all of the backup key stuff into a module.

Cargo.lock, Cargo.toml, src/bin/printer-test.rs, src/cdrw.rs, src/lib.rs, src/main.rs, src/secret_reader.rs, src/secret_writer.rs
The implementation is pretty naive but it works. This can be tested by:
- initialize the OKS instance w/ an auth value stored in an ISO & a backup key, splitting the key into one ISO for each share
```shell
$ cargo run --bin oks -- hsm initialize --secret-method iso
```
- generating keys for some collection for keyspec files
```shell
$ sudo ./target/debug/oks --state ./ca-test/ --verbose hsm generate --auth-method iso --key-spec ./ca-test/
```
- generate CA metadata & self signed certs for `openssl ca`
```shell
sudo ./target/debug/oks --state ./ca-test/ --verbose ca --auth-method iso initialize --pkcs11-path /usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so --key-spec ./ca-test/ 2>&1 | tee ca-initialize.log
```
- get passwd so we can reset yubishm
```shell
$ sudo losetup -f
/dev/loop5
$ …
```
=> Add mechanism to store and retrieve secrets from Iso files

src/cdrw.rs, src/main.rs, src/secret_reader.rs, src/secret_writer.rs
The implementation is pretty naive but it works. This can be tested by:
- initialize the OKS instance w/ an auth value stored in an Cdw & a backup key, splitting the key into one Cdw for each share
```shell
cargo run --bin oks -- --state ./ca-test/ hsm initialize --secret-method cdw 2>&1 | tee hsm-initialize.log
```
- generating keys for some collection for keyspec files 
```shell
cargo run --bin oks -- --state ./ca-test/ --verbose hsm generate --auth-method cdr --key-spec ./ca-test/
```
- generate CA metadata & self signed certs for openssl ca 
```shell
sudo ../target/debug/oks --state ./ca-test/ --verbose ca --auth-method cdr initialize --pkcs11-path /usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so --key-spec ./ca-test/ 2>&1 | tee ca-initialize.log
```
- get passwd so we can reset …
=> add Cdrw as auth and share reader & writers

src/hsm.rs, src/main.rs, src/secret_reader.rs, src/secret_writer.rs
Clap won't let us flatten both the `AuthInputArg` and `SecretOutputArg` types in the `HsmCommand::ChangeAuth` variant because their member data has naming conflicts. This is despite our explicit renaming w/ the `long` `clap` derive attribute:
```
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.18/src/builder/debug_asserts.rs:86:13:
Command change-auth: Argument names must be unique, but 'method' is in use by more than one argument or group
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
We want our auth value to end up w/ auth id 2. Before we do so we create a well known auth value w/ auth id 1. We then create a new auth value, burn it to CD, delete the old value w/ id 2, and then set the new auth value.
=> ChangeAuth: Initial implementation.

src/secret_writer.rs
My CD drive can be closed w/ the `eject` command as it is now but I'm learning that this isn't always the case. This may need work to align with the available hardware.
=> CdwSecretWriter: fixup UI elements in password writing / burning.

src/ca.rs, src/config.rs, src/main.rs
This was broken by the changes made to the auth method which included support for CDs holding auth values. This required rethinking the way we were using the environment and using the environment less is always a good thing.
=> Fix auth for the `ca sign` command.

Cargo.lock, Cargo.toml, src/bin/dcsr-pubkey.rs
This tool allows the caller to select the format (pkcs#1 vs spki) and encoding (der vs pem).
=> Add tool to extract RSA public key from a DcsrSpec.

Cargo.lock, Cargo.toml, src/bin/dac-pubkey.rs
This took currently does a few thingstwo things:
1) extract the both the issuers public key (the RoTK) as well as the
public part of the debug key (DK) from the debug cert (DC)
2) verify the signature over the DC
This is the functionality required to link the DC to both the issuer / trust anchor (RoTK) and the key being authorized to sign debug challenges (the DK).
=> Add new tool for poking around in debug cred certs

src/ca.rs
This was introduced a while back in 793ff4c.
=> Fix bug that broke authenticating to HSM through PKCS11.
